server:
  port: 8282

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/board?autoReconnect=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
